import React from 'react';
import { marked } from 'marked';
import { Logo } from './Logo';
import { InnovationReport, WorkerAgentOutput } from '../types';
import { AgentCharts } from './AgentCharts';

export const ReportView: React.FC<{ report: InnovationReport; agents?: WorkerAgentOutput[] }> = ({ report, agents }) => {
  // Aggregate all charts from all agents
  const charts = agents?.flatMap(a => a.charts || []) || [];

  return (
    <div className="bg-white text-gray-900 rounded-xl shadow-2xl overflow-hidden max-w-5xl mx-auto my-8 print:shadow-none print:my-0">
      
      {/* Decorative Header Bar */}
      <div className="h-2 bg-gradient-to-r from-pharma-900 via-pharma-accent to-pharma-900"></div>

      {/* Report Header */}
      <div className="bg-slate-50 p-10 border-b border-gray-200 flex flex-col md:flex-row justify-between items-start gap-6">
        <div>
            <div className="flex items-center gap-3 mb-4">
                <Logo className="w-10 h-10 drop-shadow-md" />
                <span className="text-xl font-bold text-pharma-900 tracking-tight">AI-PharmaX</span>
            </div>
            <h2 className="text-4xl font-serif font-bold text-gray-900 mb-2">Innovation Strategy Report</h2>
            <p className="text-gray-500 text-sm uppercase tracking-widest font-medium">Generated by Autonomous Agentic Swarm</p>
        </div>
        <div className="text-right">
            <div className="text-sm font-mono text-gray-500 mb-1">REF: APX-{Math.floor(Math.random() * 10000)}</div>
            <div className="text-sm font-mono text-gray-500 mb-4">{new Date().toLocaleDateString()}</div>
            <div className="inline-block px-4 py-1.5 bg-red-50 text-red-700 border border-red-100 rounded text-xs font-bold uppercase tracking-wider">
                Confidential Draft
            </div>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="p-10 border-b border-gray-100">
        <h3 className="text-sm font-bold text-pharma-accent uppercase tracking-widest mb-6">Executive Summary</h3>
        <div 
          className="prose prose-lg max-w-none text-gray-700 leading-relaxed font-serif prose-headings:font-bold prose-headings:text-gray-900 prose-strong:text-gray-900"
          dangerouslySetInnerHTML={{ __html: marked.parse(report.executiveSummary) as string }}
        />
      </div>

      {/* Visual Data Section - Embedded Charts */}
      {charts.length > 0 && (
        <div className="p-10 border-b border-gray-100 bg-slate-50">
           <h3 className="text-sm font-bold text-pharma-accent uppercase tracking-widest mb-6">Strategic Market Visuals</h3>
           {/* Dark container to preserve chart aesthetics */}
           <div className="bg-pharma-900 p-8 rounded-xl shadow-inner border border-pharma-800">
              <AgentCharts charts={charts} />
              <div className="mt-6 text-center border-t border-white/10 pt-4">
                 <p className="text-xs text-gray-500 font-mono">Figure 1.0: Aggregated Real-Time Agent Data Visualization</p>
              </div>
           </div>
        </div>
      )}

      {/* Dynamic Sections */}
      <div className="p-10 space-y-12 bg-white">
        {report.sections.map((section, idx) => (
            <div key={idx} className="group">
                <div className="flex items-center gap-4 mb-4">
                   <span className="text-2xl font-bold text-gray-200 group-hover:text-pharma-accent transition-colors font-mono">0{idx + 1}</span>
                   <h4 className="text-2xl font-bold text-gray-900">{section.title}</h4>
                </div>
                <div className="pl-10 border-l-2 border-gray-100 group-hover:border-pharma-accent/30 transition-colors">
                    <div 
                      className="prose max-w-none text-gray-600 whitespace-pre-wrap
                        prose-headings:font-bold prose-headings:text-gray-800 prose-headings:mt-6 prose-headings:mb-3
                        prose-p:mb-4 prose-li:my-1 prose-ul:list-disc prose-ol:list-decimal"
                      dangerouslySetInnerHTML={{ __html: marked.parse(section.content) as string }}
                    />
                </div>
            </div>
        ))}
      </div>

      {/* Final Recommendation */}
      <div className="bg-slate-900 text-white p-10 print:bg-white print:text-black print:border-t">
         <div className="max-w-3xl">
             <h3 className="text-sm font-bold text-pharma-accent uppercase tracking-widest mb-4">Final Recommendation</h3>
             <div 
                className="text-2xl font-serif leading-relaxed text-gray-200 print:text-gray-900 prose prose-invert prose-2xl prose-p:leading-relaxed"
                dangerouslySetInnerHTML={{ __html: marked.parse(report.recommendation) as string }}
             />
             <div className="mt-8 flex items-center gap-4">
                 <div className="h-px bg-white/20 flex-1"></div>
                 <div className="text-xs text-gray-500 font-mono">END OF REPORT</div>
             </div>
         </div>
      </div>
    </div>
  );
};